#==============================================================
#
#  Abs: Generate files for bumpless reboot and archiver
#
#  Name: Makefile
#
#  Facility: CAMAC Crate Verifier Controls
#
#  Auth: 30-Jun-2009, K. Luchini      (LUCHINI)
#  Rev:  dd-mmm-yyyy, First Lastname  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#       dd-mmm-yyyy, First Lastname   (USERNAME):
#         comment
#
#==============================================================
#
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

RESTORES += cv_common_autosave.cwConfig
RESTORES += cv_common.cwConfig
RESTORES += cv_common_ar.cwConfig

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
